<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Topic 5 Concepts of Probability Distributions | STA501 E-Pack: Applied Statistical Methods</title>
  <meta name="description" content="The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Topic 5 Concepts of Probability Distributions | STA501 E-Pack: Applied Statistical Methods" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Topic 5 Concepts of Probability Distributions | STA501 E-Pack: Applied Statistical Methods" />
  
  <meta name="twitter:description" content="The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Cheng Peng" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="descriptive-statistics.html"/>
<link rel="next" href="sampling-distributions.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<center><li><a href="./"><font color = "darkred"><b>STA 501 E-Pack: Applied Statistical Methods</b></font></a><br><font color = "navy">Cheng Peng</font></li></center>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html"><i class="fa fa-check"></i><b>2</b> R, RStudio and RMarkdown</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#r"><i class="fa fa-check"></i><b>2.1</b> R</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#order-of-operations"><i class="fa fa-check"></i><b>2.1.1</b> Order of Operations</a></li>
<li class="chapter" data-level="2.1.2" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#basic-r-objects"><i class="fa fa-check"></i><b>2.1.2</b> Basic R Objects</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#rstudio"><i class="fa fa-check"></i><b>2.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#rstudio-gui"><i class="fa fa-check"></i><b>2.2.1</b> RStudio GUI</a></li>
<li class="chapter" data-level="2.2.2" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#console"><i class="fa fa-check"></i><b>2.2.2</b> Console</a></li>
<li class="chapter" data-level="2.2.3" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#source-editor"><i class="fa fa-check"></i><b>2.2.3</b> Source Editor</a></li>
<li class="chapter" data-level="2.2.4" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#environment-window"><i class="fa fa-check"></i><b>2.2.4</b> Environment Window</a></li>
<li class="chapter" data-level="2.2.5" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#system-and-graphic-files"><i class="fa fa-check"></i><b>2.2.5</b> System and Graphic files</a></li>
<li class="chapter" data-level="2.2.6" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#rstudio-offers-numerous-helpful-features"><i class="fa fa-check"></i><b>2.2.6</b> RStudio offers numerous helpful features:</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#rmarkdown"><i class="fa fa-check"></i><b>2.3</b> RMarkdown</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#code-chunk"><i class="fa fa-check"></i><b>2.3.1</b> Code Chunk</a></li>
<li class="chapter" data-level="2.3.2" data-path="r-rstudio-and-rmarkdown.html"><a href="r-rstudio-and-rmarkdown.html#graphics-generated-from-r-code-chunks"><i class="fa fa-check"></i><b>2.3.2</b> Graphics Generated from R Code Chunks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html"><i class="fa fa-check"></i><b>3</b> Data Collection and Data Loading</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#sampling-plans"><i class="fa fa-check"></i><b>3.1</b> Sampling Plans</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#simple-random-sampling-srs"><i class="fa fa-check"></i><b>3.1.1</b> Simple Random Sampling (SRS)</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#systematic-sampling"><i class="fa fa-check"></i><b>3.1.2</b> Systematic sampling</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#stratified-sampling"><i class="fa fa-check"></i><b>3.1.3</b> Stratified sampling</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#study-designs"><i class="fa fa-check"></i><b>3.2</b> Study Designs</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#observational-studies"><i class="fa fa-check"></i><b>3.2.1</b> Observational Studies</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#experimental-designs"><i class="fa fa-check"></i><b>3.2.2</b> Experimental Designs</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#loading-data-to-r-from-external-data-files"><i class="fa fa-check"></i><b>3.3</b> Loading Data to R from External Data Files</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#text-file-aka.-delimited-text-file"><i class="fa fa-check"></i><b>3.3.1</b> Text File ( aka. Delimited Text File)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#data-frame-and-list"><i class="fa fa-check"></i><b>3.4</b> Data Frame and List</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="data-collection-and-data-loading.html"><a href="data-collection-and-data-loading.html#data-frame-1"><i class="fa fa-check"></i><b>3.4.1</b> Data Frame</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>4</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#data-types"><i class="fa fa-check"></i><b>4.1</b> Data Types</a></li>
<li class="chapter" data-level="4.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#tabular-and-graphic-summary"><i class="fa fa-check"></i><b>4.2</b> Tabular and Graphic Summary</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#categorical-data"><i class="fa fa-check"></i><b>4.2.1</b> Categorical Data</a></li>
<li class="chapter" data-level="4.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#numerical-data"><i class="fa fa-check"></i><b>4.2.2</b> Numerical Data</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#numerical-summary-of-numerical-data"><i class="fa fa-check"></i><b>4.3</b> Numerical Summary of Numerical Data</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#central-tendency"><i class="fa fa-check"></i><b>4.3.1</b> Central Tendency</a></li>
<li class="chapter" data-level="4.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#variations"><i class="fa fa-check"></i><b>4.3.2</b> Variations</a></li>
<li class="chapter" data-level="4.3.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#location"><i class="fa fa-check"></i><b>4.3.3</b> Location</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#assignment---descriptive-statistics"><i class="fa fa-check"></i><b>4.4</b> Assignment - Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summarizing-categorical-data"><i class="fa fa-check"></i><b>4.4.1</b> Summarizing Categorical Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html"><i class="fa fa-check"></i><b>5</b> Concepts of Probability Distributions</a>
<ul>
<li class="chapter" data-level="5.1" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#concepts-of-random-variables"><i class="fa fa-check"></i><b>5.1</b> Concepts of random variables</a></li>
<li class="chapter" data-level="5.2" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#types-of-random-variables"><i class="fa fa-check"></i><b>5.2</b> Types of random variables</a></li>
<li class="chapter" data-level="5.3" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#concepts-of-probability-distributions-1"><i class="fa fa-check"></i><b>5.3</b> Concepts of probability distributions</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#concepts-of-probability"><i class="fa fa-check"></i><b>5.3.1</b> Concepts of probability</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#probability-distribution-of-random-variables"><i class="fa fa-check"></i><b>5.4</b> Probability distribution of random variables</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#discrete-probability-distribution"><i class="fa fa-check"></i><b>5.4.1</b> Discrete probability distribution</a></li>
<li class="chapter" data-level="5.4.2" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#continuous-probability-distribution"><i class="fa fa-check"></i><b>5.4.2</b> Continuous probability distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#special-continuous-distributions"><i class="fa fa-check"></i><b>5.5</b> Special Continuous Distributions</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#normal-distribution"><i class="fa fa-check"></i><b>5.5.1</b> Normal Distribution</a></li>
<li class="chapter" data-level="5.5.2" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#t-distribution"><i class="fa fa-check"></i><b>5.5.2</b> t distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#summary"><i class="fa fa-check"></i><b>5.6</b> Summary</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#numerical-examples-based-on-normal-and-t-distributions"><i class="fa fa-check"></i><b>5.6.1</b> Numerical Examples Based on Normal and t Distributions</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="concepts-of-probability-distributions.html"><a href="concepts-of-probability-distributions.html#assignment---probability-distributions"><i class="fa fa-check"></i><b>5.7</b> Assignment - Probability Distributions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling-distributions.html"><a href="sampling-distributions.html"><i class="fa fa-check"></i><b>6</b> Sampling Distributions</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sampling-distributions.html"><a href="sampling-distributions.html#concepts-of-the-sampling-distribution"><i class="fa fa-check"></i><b>6.1</b> Concepts of the sampling distribution</a></li>
<li class="chapter" data-level="6.2" data-path="sampling-distributions.html"><a href="sampling-distributions.html#sampling-distribution-of-sampling-means"><i class="fa fa-check"></i><b>6.2</b> Sampling Distribution of Sampling Means</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="sampling-distributions.html"><a href="sampling-distributions.html#working-data-set-plant-diversity"><i class="fa fa-check"></i><b>6.2.1</b> Working Data Set: Plant Diversity</a></li>
<li class="chapter" data-level="6.2.2" data-path="sampling-distributions.html"><a href="sampling-distributions.html#normal-population-with-given-mean-mu-and-variance-sigma2"><i class="fa fa-check"></i><b>6.2.2</b> Normal Population with given mean (<span class="math inline">\(\mu\)</span>) and Variance (<span class="math inline">\(\sigma^2\)</span>)</a></li>
<li class="chapter" data-level="6.2.3" data-path="sampling-distributions.html"><a href="sampling-distributions.html#normal-population-with-a-given-mean-mu-and-an-unknown-variance-sigma2"><i class="fa fa-check"></i><b>6.2.3</b> Normal Population with a given mean (<span class="math inline">\(\mu\)</span>) and an <strong>Unknown</strong> Variance (<span class="math inline">\(\sigma^2\)</span>)</a></li>
<li class="chapter" data-level="6.2.4" data-path="sampling-distributions.html"><a href="sampling-distributions.html#unspecified-population-with-a-given-mean-muand-an-unspecifed-variance-sigma2"><i class="fa fa-check"></i><b>6.2.4</b> Unspecified Population with a given mean (<span class="math inline">\(\mu\)</span>)and an unspecifed variance (<span class="math inline">\(\sigma^2\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sampling-distributions.html"><a href="sampling-distributions.html#sampling-distribution-of-sample-proportions"><i class="fa fa-check"></i><b>6.3</b> Sampling distribution of sample proportions</a></li>
<li class="chapter" data-level="6.4" data-path="sampling-distributions.html"><a href="sampling-distributions.html#summary-1"><i class="fa fa-check"></i><b>6.4</b> Summary</a></li>
<li class="chapter" data-level="6.5" data-path="sampling-distributions.html"><a href="sampling-distributions.html#assignment---sampling-distributions"><i class="fa fa-check"></i><b>6.5</b> Assignment - Sampling Distributions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>7</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="7.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#some-terms"><i class="fa fa-check"></i><b>7.1</b> Some Terms</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#what-are-the-issues-of-a-point-estimate"><i class="fa fa-check"></i><b>7.1.1</b> What are the issues of a point estimate?</a></li>
<li class="chapter" data-level="7.1.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#how-about-multiple-samples"><i class="fa fa-check"></i><b>7.1.2</b> How About Multiple Samples?</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#how-to-find-the-confidence-intervals-for-means-and-proportions"><i class="fa fa-check"></i><b>7.2</b> How to find the Confidence Intervals for Means and Proportions?</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#framework-of-confidence-interval"><i class="fa fa-check"></i><b>7.2.1</b> Framework Of Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-interval-of-population-mean"><i class="fa fa-check"></i><b>7.3</b> Confidence Interval of Population Mean</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#normal-population-with-known-variance."><i class="fa fa-check"></i><b>7.3.1</b> Normal Population with Known Variance.</a></li>
<li class="chapter" data-level="7.3.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#normal-population-with-unknown-variance"><i class="fa fa-check"></i><b>7.3.2</b> Normal Population with Unknown Variance</a></li>
<li class="chapter" data-level="7.3.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#unspecified-population-with-unknown-variance-but-with-large-sample-sizes"><i class="fa fa-check"></i><b>7.3.3</b> Unspecified Population with Unknown Variance but with Large Sample Sizes</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-interval-of-proportion"><i class="fa fa-check"></i><b>7.4</b> Confidence Interval of Proportion</a></li>
<li class="chapter" data-level="7.5" data-path="confidence-intervals.html"><a href="confidence-intervals.html#two-sample-problems---comparing-two-population-means"><i class="fa fa-check"></i><b>7.5</b> Two Sample Problems - Comparing Two Population Means</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-interval-of-the-difference-of-two-unspecified-populations-means"><i class="fa fa-check"></i><b>7.5.1</b> Confidence Interval of the Difference of Two Unspecified Populations Means</a></li>
<li class="chapter" data-level="7.5.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-interval-of-the-difference-of-two-normal-populations-means"><i class="fa fa-check"></i><b>7.5.2</b> Confidence Interval of the Difference of Two Normal Populations Means</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="confidence-intervals.html"><a href="confidence-intervals.html#assignment---confidence-intervals"><i class="fa fa-check"></i><b>7.6</b> Assignment - Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html"><i class="fa fa-check"></i><b>8</b> Testing Statistical Hypothesis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#formulation-of-statistical-hypothesis-testing"><i class="fa fa-check"></i><b>8.1</b> Formulation of Statistical Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#null-and-alternative-hypotheses"><i class="fa fa-check"></i><b>8.1.1</b> Null and Alternative Hypotheses</a></li>
<li class="chapter" data-level="8.1.2" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#relationship-between-the-claim-and-the-statistical-hypotheses"><i class="fa fa-check"></i><b>8.1.2</b> Relationship between the claim and the statistical hypotheses</a></li>
<li class="chapter" data-level="8.1.3" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#test-statistics---statistical-evidence"><i class="fa fa-check"></i><b>8.1.3</b> Test Statistics - Statistical Evidence</a></li>
<li class="chapter" data-level="8.1.4" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#types-of-test-and-rejection-region"><i class="fa fa-check"></i><b>8.1.4</b> Types of Test and Rejection Region</a></li>
<li class="chapter" data-level="8.1.5" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#statistical-decision-rule-p-value"><i class="fa fa-check"></i><b>8.1.5</b> Statistical Decision Rule: p-value</a></li>
<li class="chapter" data-level="8.1.6" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#summary-of-the-test-hypothesis-procedure"><i class="fa fa-check"></i><b>8.1.6</b> Summary of the Test Hypothesis Procedure</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#case-studies"><i class="fa fa-check"></i><b>8.2</b> Case Studies</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#case-i-normal-population-with-a-known-variance."><i class="fa fa-check"></i><b>8.2.1</b> Case I: normal population with a known variance.</a></li>
<li class="chapter" data-level="8.2.2" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#case-ii-normal-population-with-an-unknown-variance"><i class="fa fa-check"></i><b>8.2.2</b> Case II: Normal population with an unknown variance</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#unspecified-population-with-an-unknown-variance---clt"><i class="fa fa-check"></i><b>8.3</b> Unspecified population with an unknown variance - CLT</a></li>
<li class="chapter" data-level="8.4" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#testing-population-proportion"><i class="fa fa-check"></i><b>8.4</b> Testing Population Proportion</a></li>
<li class="chapter" data-level="8.5" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#testing-the-difference-between-two-population-means"><i class="fa fa-check"></i><b>8.5</b> Testing the difference between two population means</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#both-populations-are-unspecified-and-sample-sizes-are-large."><i class="fa fa-check"></i><b>8.5.1</b> Both populations are unspecified and sample sizes are large.</a></li>
<li class="chapter" data-level="8.5.2" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#both-populations-are-normal-with-unknown-but-equal-variances"><i class="fa fa-check"></i><b>8.5.2</b> Both populations are normal with unknown but equal variances</a></li>
<li class="chapter" data-level="8.5.3" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#paired-t-test"><i class="fa fa-check"></i><b>8.5.3</b> Paired t-test</a></li>
<li class="chapter" data-level="8.5.4" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#concluding-remarks"><i class="fa fa-check"></i><b>8.5.4</b> Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="testing-statistical-hypothesis.html"><a href="testing-statistical-hypothesis.html#practice-problems"><i class="fa fa-check"></i><b>8.6</b> Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html"><i class="fa fa-check"></i><b>9</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#the-question-of-one-way-anova"><i class="fa fa-check"></i><b>9.1</b> The Question of One-way ANOVA</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#what-is-anova"><i class="fa fa-check"></i><b>9.1.1</b> What is ANOVA</a></li>
<li class="chapter" data-level="9.1.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#assumptions-of-anova"><i class="fa fa-check"></i><b>9.1.2</b> Assumptions of ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#steps-of-anova"><i class="fa fa-check"></i><b>9.2</b> Steps of ANOVA</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#anova-tables"><i class="fa fa-check"></i><b>9.2.1</b> ANOVA Tables</a></li>
<li class="chapter" data-level="9.2.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#post-hoc-pairwise-comparison"><i class="fa fa-check"></i><b>9.2.2</b> Post hoc Pairwise Comparison</a></li>
<li class="chapter" data-level="9.2.3" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#how-to-summarize-anova-results"><i class="fa fa-check"></i><b>9.2.3</b> How to Summarize ANOVA Results</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#welchs-anova"><i class="fa fa-check"></i><b>9.3</b> Welch’s ANOVA</a></li>
<li class="chapter" data-level="9.4" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#case-study-mussel-length-example---solution"><i class="fa fa-check"></i><b>9.4</b> Case Study: Mussel Length Example - Solution</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#creating-an-anova-table"><i class="fa fa-check"></i><b>9.4.1</b> Creating An ANOVA Table</a></li>
<li class="chapter" data-level="9.4.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#diagnostic-analysis"><i class="fa fa-check"></i><b>9.4.2</b> Diagnostic Analysis</a></li>
<li class="chapter" data-level="9.4.3" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#welch-anova"><i class="fa fa-check"></i><b>9.4.3</b> Welch ANOVA</a></li>
<li class="chapter" data-level="9.4.4" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#post-hoc-multiple-comparisons"><i class="fa fa-check"></i><b>9.4.4</b> Post-hoc Multiple Comparisons</a></li>
<li class="chapter" data-level="9.4.5" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#visual-comparison---boxplots"><i class="fa fa-check"></i><b>9.4.5</b> Visual Comparison - Boxplots</a></li>
<li class="chapter" data-level="9.4.6" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#anova-reporting"><i class="fa fa-check"></i><b>9.4.6</b> ANOVA Reporting</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#practice-problems-1"><i class="fa fa-check"></i><b>9.5</b> Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html"><i class="fa fa-check"></i><b>10</b> Correlation and Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#the-question-and-the-data"><i class="fa fa-check"></i><b>10.1</b> The question and the data</a></li>
<li class="chapter" data-level="10.2" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#visual-inspection-for-association"><i class="fa fa-check"></i><b>10.2</b> Visual Inspection for Association</a></li>
<li class="chapter" data-level="10.3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#coefficient-of-correlation"><i class="fa fa-check"></i><b>10.3</b> Coefficient of Correlation</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#definition-of-pearson-correlation-coefficient"><i class="fa fa-check"></i><b>10.3.1</b> Definition of Pearson correlation coefficient</a></li>
<li class="chapter" data-level="10.3.2" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#interpretation-of-correlation-coefficient"><i class="fa fa-check"></i><b>10.3.2</b> Interpretation of correlation coefficient</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#least-square-regression-structure-diagnostics-and-applications"><i class="fa fa-check"></i><b>10.4</b> Least square regression: structure, diagnostics, and applications</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#definitions"><i class="fa fa-check"></i><b>10.4.1</b> Definitions</a></li>
<li class="chapter" data-level="10.4.2" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#assumptions-of-least-square-regression"><i class="fa fa-check"></i><b>10.4.2</b> Assumptions of Least Square Regression</a></li>
<li class="chapter" data-level="10.4.3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#model-building-and-diagnostics"><i class="fa fa-check"></i><b>10.4.3</b> Model Building and Diagnostics</a></li>
<li class="chapter" data-level="10.4.4" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#residual-diagnostics-and-remedies"><i class="fa fa-check"></i><b>10.4.4</b> Residual Diagnostics and Remedies</a></li>
<li class="chapter" data-level="10.4.5" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#final-model-with-applications"><i class="fa fa-check"></i><b>10.4.5</b> Final Model with Applications</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#case-study-amyotrophic-lateral-sclerosis-analysis-revisited"><i class="fa fa-check"></i><b>10.5</b> Case Study: Amyotrophic lateral sclerosis analysis revisited</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#objectives"><i class="fa fa-check"></i><b>10.5.1</b> Objectives</a></li>
<li class="chapter" data-level="10.5.2" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#model-fitting"><i class="fa fa-check"></i><b>10.5.2</b> Model Fitting</a></li>
<li class="chapter" data-level="10.5.3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#box-cox-transformation"><i class="fa fa-check"></i><b>10.5.3</b> Box-Cox Transformation</a></li>
<li class="chapter" data-level="10.5.4" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html#model-applications"><i class="fa fa-check"></i><b>10.5.4</b> Model Applications</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html"><i class="fa fa-check"></i><b>11</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-practical-question"><i class="fa fa-check"></i><b>11.1</b> The Practical Question</a></li>
<li class="chapter" data-level="11.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-process-of-building-a-multiple-linear-regression-model"><i class="fa fa-check"></i><b>11.2</b> The Process of Building A Multiple Linear Regression Model</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#assumptions-of-mlr"><i class="fa fa-check"></i><b>11.2.1</b> Assumptions of MLR</a></li>
<li class="chapter" data-level="11.2.2" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#the-structure-of-mlr"><i class="fa fa-check"></i><b>11.2.2</b> The Structure of MLR</a></li>
<li class="chapter" data-level="11.2.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#more-on-model-specifications"><i class="fa fa-check"></i><b>11.2.3</b> More on Model Specifications</a></li>
<li class="chapter" data-level="11.2.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#estimation-of-regression-coefficients"><i class="fa fa-check"></i><b>11.2.4</b> Estimation of Regression Coefficients</a></li>
<li class="chapter" data-level="11.2.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#model-diagnostics"><i class="fa fa-check"></i><b>11.2.5</b> Model Diagnostics</a></li>
<li class="chapter" data-level="11.2.6" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#goodness-of-fit-and-variable-selection"><i class="fa fa-check"></i><b>11.2.6</b> Goodness-of-fit and Variable Selection</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#case-study-1"><i class="fa fa-check"></i><b>11.3</b> Case Study 1</a></li>
<li class="chapter" data-level="11.4" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#case-study-2"><i class="fa fa-check"></i><b>11.4</b> Case Study 2</a></li>
<li class="chapter" data-level="11.5" data-path="multiple-linear-regression.html"><a href="multiple-linear-regression.html#practice-problems-2"><i class="fa fa-check"></i><b>11.5</b> Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html"><i class="fa fa-check"></i><b>12</b> Logistic Regression Models</a>
<ul>
<li class="chapter" data-level="12.1" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#motivational-example-and-practical-question"><i class="fa fa-check"></i><b>12.1</b> Motivational Example and Practical Question</a></li>
<li class="chapter" data-level="12.2" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#logistic-regression-models-and-applications"><i class="fa fa-check"></i><b>12.2</b> Logistic Regression Models and Applications</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#the-structure-of-logistic-regression-model"><i class="fa fa-check"></i><b>12.2.1</b> The Structure of Logistic Regression Model</a></li>
<li class="chapter" data-level="12.2.2" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#assumptions-and-diagnostics"><i class="fa fa-check"></i><b>12.2.2</b> Assumptions and Diagnostics</a></li>
<li class="chapter" data-level="12.2.3" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#coefficient-estimation-and-interpretation"><i class="fa fa-check"></i><b>12.2.3</b> Coefficient Estimation and Interpretation</a></li>
<li class="chapter" data-level="12.2.4" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#use-of-glm-and-annotations"><i class="fa fa-check"></i><b>12.2.4</b> Use of <strong>glm()</strong> and Annotations</a></li>
<li class="chapter" data-level="12.2.5" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#applications-of-logistic-regression-models"><i class="fa fa-check"></i><b>12.2.5</b> Applications of Logistic Regression Models</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#case-studies-1"><i class="fa fa-check"></i><b>12.3</b> Case Studies</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#the-simple-logistic-regression-model"><i class="fa fa-check"></i><b>12.3.1</b> The simple logistic regression model</a></li>
<li class="chapter" data-level="12.3.2" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#multiple-logistic-regression-model"><i class="fa fa-check"></i><b>12.3.2</b> Multiple Logistic Regression Model</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="logistic-regression-models.html"><a href="logistic-regression-models.html#practice-problems-3"><i class="fa fa-check"></i><b>12.4</b> Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html"><i class="fa fa-check"></i><b>13</b> Contingency Table Analysis</a>
<ul>
<li class="chapter" data-level="13.1" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#the-motivational-examples"><i class="fa fa-check"></i><b>13.1</b> The Motivational Examples</a></li>
<li class="chapter" data-level="13.2" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#two-way-contingency-tables-and-analysis"><i class="fa fa-check"></i><b>13.2</b> Two-way Contingency Tables and Analysis</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#the-structure-of-two-way-contingency-table"><i class="fa fa-check"></i><b>13.2.1</b> The Structure of Two-way Contingency Table</a></li>
<li class="chapter" data-level="13.2.2" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#pearson-chi2-test-of-independence"><i class="fa fa-check"></i><b>13.2.2</b> Pearson <span class="math inline">\(\chi^2\)</span> Test of Independence</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#measures-of-association"><i class="fa fa-check"></i><b>13.3</b> Measures of Association</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#times2-table-under-different-study-designs"><i class="fa fa-check"></i><b>13.3.1</b> <span class="math inline">\(2\times2\)</span>-table Under Different Study Designs</a></li>
<li class="chapter" data-level="13.3.2" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#measures-of-association-1"><i class="fa fa-check"></i><b>13.3.2</b> Measures of Association</a></li>
<li class="chapter" data-level="13.3.3" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#validity-of-measures-of-association"><i class="fa fa-check"></i><b>13.3.3</b> Validity of Measures of Association</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#case-studies-2"><i class="fa fa-check"></i><b>13.4</b> Case Studies</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#case-study-1-1"><i class="fa fa-check"></i><b>13.4.1</b> Case Study 1</a></li>
<li class="chapter" data-level="13.4.2" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#case-study-2-1"><i class="fa fa-check"></i><b>13.4.2</b> Case Study 2</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="contingency-table-analysis.html"><a href="contingency-table-analysis.html#practice-problems-4"><i class="fa fa-check"></i><b>13.5</b> Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html"><i class="fa fa-check"></i><b>14</b> Analysis of Counts and Rates</a>
<ul>
<li class="chapter" data-level="14.1" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#motivational-examples"><i class="fa fa-check"></i><b>14.1</b> Motivational Examples</a></li>
<li class="chapter" data-level="14.2" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#poisson-regression-for-counts-and-rates"><i class="fa fa-check"></i><b>14.2</b> Poisson Regression for Counts and Rates</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#structure-and-interpretations"><i class="fa fa-check"></i><b>14.2.1</b> Structure and Interpretations</a></li>
<li class="chapter" data-level="14.2.2" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#assumptions-and-goodness-of-fit"><i class="fa fa-check"></i><b>14.2.2</b> Assumptions and Goodness-of-fit</a></li>
<li class="chapter" data-level="14.2.3" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#dispersion-issue-and-remedies"><i class="fa fa-check"></i><b>14.2.3</b> Dispersion Issue and Remedies</a></li>
<li class="chapter" data-level="14.2.4" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#data-structure-of-poisson-regression"><i class="fa fa-check"></i><b>14.2.4</b> Data Structure of Poisson Regression</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#case-studies-3"><i class="fa fa-check"></i><b>14.3</b> Case Studies</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#harbor-seal-data"><i class="fa fa-check"></i><b>14.3.1</b> Harbor Seal Data</a></li>
<li class="chapter" data-level="14.3.2" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#toxicity-study"><i class="fa fa-check"></i><b>14.3.2</b> Toxicity Study</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#concluding-remarks-1"><i class="fa fa-check"></i><b>14.4</b> Concluding Remarks</a></li>
<li class="chapter" data-level="14.5" data-path="analysis-of-counts-and-rates.html"><a href="analysis-of-counts-and-rates.html#practice-problems-5"><i class="fa fa-check"></i><b>14.5</b> Practice Problems</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html"><i class="fa fa-check"></i><b>15</b> Power Calculation and Sample Size Determination</a>
<ul>
<li class="chapter" data-level="15.1" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#two-sample-proportion-problems"><i class="fa fa-check"></i><b>15.1</b> Two-sample Proportion Problems</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#sample-size-estimations-for-two-proportions"><i class="fa fa-check"></i><b>15.1.1</b> Sample size estimations for <strong>two proportions</strong></a></li>
<li class="chapter" data-level="15.1.2" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#power-analysis-for-two-proportions"><i class="fa fa-check"></i><b>15.1.2</b> Power analysis for <strong>two proportions</strong></a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#two-sample-mean-problems"><i class="fa fa-check"></i><b>15.2</b> Two-sample Mean Problems</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#sample-size-estimations-for-two-averages"><i class="fa fa-check"></i><b>15.2.1</b> Sample size estimations for <strong>two averages</strong></a></li>
<li class="chapter" data-level="15.2.2" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#power-analysis-for-two-averages"><i class="fa fa-check"></i><b>15.2.2</b> Power analysis for two averages</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#paired-sample-problems"><i class="fa fa-check"></i><b>15.3</b> Paired-sample Problems</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#sample-size-estimation-for-paired-data-before-and-after"><i class="fa fa-check"></i><b>15.3.1</b> Sample size estimation for <strong>paired data (before and after)</strong></a></li>
<li class="chapter" data-level="15.3.2" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#power-analysis-of-paired-samples-paired-t-test"><i class="fa fa-check"></i><b>15.3.2</b> Power analysis of <strong>paired samples (paired t-test)</strong></a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#unequal-sample-sizes-problems"><i class="fa fa-check"></i><b>15.4</b> Unequal Sample Sizes Problems</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#power-analysis-with-unequal-sample-sizes"><i class="fa fa-check"></i><b>15.4.1</b> Power analysis with <strong>unequal sample sizes</strong></a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="power-calculation-and-sample-size-determination.html"><a href="power-calculation-and-sample-size-determination.html#conclusions"><i class="fa fa-check"></i><b>15.5</b> Conclusions</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STA501 E-Pack: Applied Statistical Methods</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="concepts-of-probability-distributions" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Topic 5</span> Concepts of Probability Distributions<a href="concepts-of-probability-distributions.html#concepts-of-probability-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, we provide a non-technical description of random variables and their corresponding probability distributions.</p>
<div id="concepts-of-random-variables" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Concepts of random variables<a href="concepts-of-probability-distributions.html#concepts-of-random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A random variable is a variable and its value is dependent on chance. What is the difference between a “regular” variable we learned from middle school and a <strong>random variable</strong>?</p>
<ul>
<li><p><strong>Example 1</strong>: Let <span class="math inline">\(x\)</span> be a variable in the equation <span class="math inline">\(3x +4 = 8\)</span>. <span class="math inline">\(x\)</span> is unknown before you solve for it from the equation. Most importantly, it is a <strong>fixed</strong> value although it is unknown.</p></li>
<li><p><strong>Example 2</strong>: Let <span class="math inline">\(Y\)</span> be the height of the WCU student population. <span class="math inline">\(Y\)</span> is unknown before you measure the height of a student from this population. However, which student is selected to measure his/her height is dependent on <strong>the chance</strong>!</p></li>
</ul>
<p>We can see from examples 1 and 2 that <span class="math inline">\(x\)</span> and <span class="math inline">\(Y\)</span> are variables. <span class="math inline">\(x\)</span> is a <strong>“regular” variable</strong> and <span class="math inline">\(Y\)</span> is a <strong>random variable</strong>!</p>
<p>Because the value of a random variable is <strong>dependent on the chance</strong>, we need additional mathematical tools to characterize the <strong>chance</strong> - probability distribution. This will be described in a non-technical manner in the next section.</p>
</div>
<div id="types-of-random-variables" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Types of random variables<a href="concepts-of-probability-distributions.html#types-of-random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are basic types of random variables: discrete and continuous random variables.</p>
<ul>
<li><p><strong>Discrete random variables</strong>: A random variable is said to be discrete if its value is obtained by <font color = "red"><strong>counting</strong></font>. A discrete random variable may have either finite or infinite distinct values.</p>
<ul>
<li><p><strong>Example 3</strong>: <em>Coin Flipping Experiment</em> - Consider flipping an unfair coin (like the ones in the left panel of Figure 1) 10 times. Let <span class="math inline">\(X=\)</span> the number of <strong>heads</strong> observed. <span class="math inline">\(X\)</span> is a discrete random variable since it can take finite values (11 distinct values): 0, 1, 2, …, 10. Further, it can only take more than 11 distinct values since the unfair coin was flipped 10 times! Moreover, <span class="math inline">\(X\)</span> can never be 2.7! It is discrete!</p></li>
<li><p><strong>Example 4</strong>: <em>Quadrat Sampling (right panel of Figure 1)</em> - Consider estimating the total number of dandelions in a field. We know or we can measure the area of the field. The area of the quadrat is fixed. We can throw the quadrat randomly to the different regions in the field multiple times and count the number of dandelions in the squared plots sampled. Since the ratio of the sampled area and the total area of the field is equal to the ratio of the total number of dandelions in the sampled area and the total number of dandelions in the field. We then can solve the equation for the estimated total number of dandelions in the field. Now, let <span class="math inline">\(Y\)</span> be the number of dandelions inside the quadrat in each sampled region. Clearly, <span class="math inline">\(Y\)</span> is discrete. Is <span class="math inline">\(Y\)</span> finite? Technically speaking, the number of dandelions in the quadrat cannot be infinite no matter where it is placed. However, unlike <span class="math inline">\(X\)</span> in Example 3 which is naturally capped by 11, no cap can be placed on <span class="math inline">\(Y\)</span>. Theoretically speaking, <span class="math inline">\(Y\)</span> is infinite!</p></li>
</ul></li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-57"></span>
<img src="img04/w04-UnfairCoin-DandelionsSampling.jpg" alt=" Left: unfair coins. Right: quadrat for ecology sampling - estimating the number of dandelions in a field." width="90%" />
<p class="caption">
Figure 5.1:  Left: unfair coins. Right: quadrat for ecology sampling - estimating the number of dandelions in a field.
</p>
</div>
<ul>
<li><p><strong>Continuous random variables</strong> A random variable is continuous if its value is obtained by <font color = "red"><strong>measuring</strong></font>.</p>
<ul>
<li><strong>Example 5</strong>: Let <span class="math inline">\(Y\)</span> be the pH of arterial plasma (i.e., the acidity of the blood) of people of a population. <span class="math inline">\(Y\)</span> is a typical continuous random variable. It has uncountably many values <strong>between 0 and 14</strong>. It is continuous since any value between any selected pHs could be the pH of a person in the population.</li>
</ul></li>
</ul>
</div>
<div id="concepts-of-probability-distributions-1" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Concepts of probability distributions<a href="concepts-of-probability-distributions.html#concepts-of-probability-distributions-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We first briefly describe the concept of probability and then outline the probability distributions of random variables.</p>
<div id="concepts-of-probability" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Concepts of probability<a href="concepts-of-probability-distributions.html#concepts-of-probability" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before introducing the definition of probability, we list the following concepts.</p>
<ul>
<li><p><strong>(Statistical) Experiment</strong> - a process that produces well-defined outcomes. For example, consider an experiment of flipping a fair coin, the possible outcomes of this experiment are {heads, tails}.</p></li>
<li><p><strong>Sample Space</strong> - The set of all possible outcomes is called sample space. The <strong>sample space</strong> of the above coin-toss example is <strong>S = {heads, tails}</strong>.</p>
<ul>
<li><strong>Example 6</strong>: Consider an experiment of flipping a fair coin <em>sequentially</em> three times. We use <strong>T</strong> to denote <strong>tails</strong> and <strong>H</strong> for <strong>heads</strong>. The sample space of this experiment is given by <strong>S = {TTT, TTH, THT, HTT, HHH, HHT, HTH, THH}</strong> which can be explained by the following figure.</li>
</ul></li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-58"></span>
<img src="img04/w04-coin-tossing-exp.jpg" alt="Sample space of the experiment of flipping a coin three times." width="80%" />
<p class="caption">
Figure 5.2: Sample space of the experiment of flipping a coin three times.
</p>
</div>
<ul>
<li><p><strong>Event</strong> - a subset of sample space. Two extreme events are the impossible event (i.e., the subset is empty) and the sure event (i.e., the subset is equal to the sample space).</p>
<ul>
<li><strong>Example 7</strong>: We will define a few events based on the experiment in <strong>Example 6</strong> in the following.
<ul>
<li>E1 = {observing at least 2 heads} = {HHH, HTH, THH, HHT}.</li>
<li>E2 = {observing exactly one heads} = {HTT, THT, TTH}.</li>
<li>E3 = {observing 5 heads} = {} = empty set = impossible event.</li>
<li>E4 = {observing at one heads <strong>OR</strong> one tails} = <strong>S</strong> = sure event.</li>
</ul></li>
<li><strong>Example 8</strong>: We still use the experiment in <strong>Example 6</strong> with sample space <strong>S = {TTT, TTH, THT, HTT, HHH, HHT, HTH, THH}</strong>. Define <span class="math inline">\(Y =\)</span> the number of <strong>heads</strong> observed in the experiment. We now define <strong>Events</strong> based on the value of random variable <span class="math inline">\(Y\)</span>.
<ul>
<li>E.0 = {Y=0} = {TTT}.</li>
<li>E.1 = {Y=1} = {TTH, THT, HTT}.</li>
<li>E.2 = {Y=2} = {THH, HTH, HHT}.</li>
<li>E.3 = {Y=1} = {HHH}.</li>
</ul></li>
</ul></li>
<li><p><strong>Definitions of probability</strong> - Two technical definitions of probability measure the chance of occurrence of an event.</p>
<ul>
<li><p><em>Classical probability (based on equally likely outcome)</em>: P(E) = (# outcomes in E)/(# outcomes in S).</p>
<ul>
<li><strong>Example 9</strong>: The experiment in <strong>Example 6</strong> is an equally likely outcome experiment. Based on the above definition, we can calculate the probability of the event in <strong>Example 7</strong>:
<ul>
<li>P(E1) = #E1/#S = 4/8 = 1/2.</li>
<li>P(E2) = #E2/#S = 3/8.</li>
<li>P(E3) = #E3/#S = 0/8 = 0. That is, an impossible event has a probability of 0.</li>
<li>P(E4) = #E4/#S = #S/#S = 1. That is, a sure event has probability 1.</li>
</ul></li>
</ul></li>
<li><p><em>Relative frequency approximation</em> - If an event is defined based on an unequally likely experiment, we need to repeat the experiment multiple times to observe the number of occurrences and then use the relative frequency to <strong>approximate</strong> the probability of the event. This definition is used in most practical applications.</p>
<ul>
<li><strong>Example 10</strong>: Chronic arsenic toxicity, which is due to low-concentration exposure over a long period of time, impairs the same organs and tissues and is a threat to public health. The following map shows the distribution of people with arsenic levels &gt; 10 <span class="math inline">\(\mu g/L\)</span> by US counties. As an example, Maine is one of the few states with a high level of arsenic. Let’s consider a remote northern Maine community where no public water system is available, the drinking water is from private wells. What is the probability that a long-term resident of the community has an arsenic level of more than 10 <span class="math inline">\(\mu g/L\)</span>? Apparently, that probability is NOT 0.5 (i.e., this is not an equally likely outcome experiment). We survey many residents to measure the arsenic level for each selected resident and record whether the arsenic level is higher than 10 <span class="math inline">\(\mu g/L\)</span>. The desired probability is approximated by the relative frequency of residents with an arsenic level higher than 10 <span class="math inline">\(\mu g/L\)</span>.</li>
</ul></li>
</ul></li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-59"></span>
<img src="img04/w04-CountyMapForArsenicDist.jpg" alt="Distribution of people with arsenic level &gt; 10 ug/L by US counties" width="80%" />
<p class="caption">
Figure 5.3: Distribution of people with arsenic level &gt; 10 ug/L by US counties
</p>
</div>
</div>
</div>
<div id="probability-distribution-of-random-variables" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Probability distribution of random variables<a href="concepts-of-probability-distributions.html#probability-distribution-of-random-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The probability distribution of a population (or random variable) contains <strong>all information</strong> in the population (random variable). The primary questions we need to answer frequently about the distributions.</p>
<ul>
<li><p><strong>Finding probabilities</strong>: For any given two values, say <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, (including one or both of the extreme values), we can find the probability <span class="math inline">\(P(x_1 &lt; X &lt; x_2)\)</span>.</p></li>
<li><p><strong>Finding quantiles (specific values of the random variable)</strong>: For any value <span class="math inline">\(x\)</span> (including one of the extreme values) and a probability, say <span class="math inline">\(p_0\)</span>, of a well-defined event, we can find the specific value of <span class="math inline">\(Y\)</span>, say <span class="math inline">\(x_0\)</span> that was used to define the valid event, from the equation <span class="math inline">\(P(x &lt; X &lt;x_0) = p_0\)</span> or <span class="math inline">\(P(x_0 &lt; X &lt;x) = p_0\)</span>.</p></li>
</ul>
<p>There are types of random variables: discrete random variables and continuous random variables. The probability distribution of a random variable provides a way to find the probability of an event defined by a value or a set of values of the random variable.</p>
<div id="discrete-probability-distribution" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Discrete probability distribution<a href="concepts-of-probability-distributions.html#discrete-probability-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The probability distribution of a discrete random variable is a description of the relative frequencies of the corresponding district values.</p>
<ul>
<li><strong>Example 11</strong>: Refer to <strong>Example 9</strong>, Let <span class="math inline">\(Y\)</span> be the number of children. <span class="math inline">\(Y\)</span> has 4 possible values: 0, 1, 2, 3. Then the probability of each distinct value of <span class="math inline">\(Y\)</span> is summarized in the following table.</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-60">Table 5.1: </span>Probability Distribution Table</caption>
<thead>
<tr class="header">
<th align="right">Y</th>
<th align="right">Prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">0.125</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">0.375</td>
</tr>
<tr class="odd">
<td align="right">2</td>
<td align="right">0.375</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="right">0.125</td>
</tr>
</tbody>
</table>
<p>With the above table, we can find the probability of all events defined based on the values of random variable <span class="math inline">\(Y\)</span>. The above table is called the <strong>probability distribution table</strong>. The following graphic representation of the probability distribution table is called the <strong>probability distribution histogram</strong>.</p>
<p><img src="STA501EB_files/figure-html/unnamed-chunk-61-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>For example, with the above table, we can two types of questions.</p>
<ul>
<li><strong>Finding probabilities</strong>
<ul>
<li><span class="math inline">\(P(Y &lt; 2) = P(0&lt; X &lt; 2) = P(Y=0) + P(Y = 1) = 0.125 + 0.375 = 0.5\)</span>.</li>
<li><span class="math inline">\(P(Y &gt; 2) = P(2 &lt; X \le 3) = P(Y = 3) = 0.125\)</span>.</li>
</ul></li>
<li><strong>Finding quantiles</strong>
<ul>
<li><span class="math inline">\(P(0&lt; X &lt; x_0) = 0.5 \to x_0 = 1.\)</span></li>
<li><span class="math inline">\(P(1&lt;X&lt;x_0) = 0.375 \to x_0 = 0.375.\)</span></li>
</ul></li>
</ul>
<p><strong>Caution</strong>: The above two types of questions can be complicated in discrete distribution. This <a href="https://valelab4.ucsf.edu/svn/3rdpartypublic/boost/libs/math/doc/sf_and_dist/html/math_toolkit/policy/pol_tutorial/understand_dis_quant.html">blog post</a> explains this complexity in some detail. We will NOT use the discrete distribution directly in this class, instead, we use will the normal distribution (in the next section).</p>
<p><strong>Remark</strong>: We can see from the above examples that the definition of an event associated with a discrete random variable is a value or set of values.</p>
</div>
<div id="continuous-probability-distribution" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Continuous probability distribution<a href="concepts-of-probability-distributions.html#continuous-probability-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A continuous random variable has uncountably many distinct values. That is, for any two distinct values of the continuous random variable, no matter how close they are, there are still uncountably many values in between. because this property, <strong>an event associated with a continuous random variable is defined to be an interval or the union of some intervals of the values of the random variable</strong>.</p>
<p><img src="STA501EB_files/figure-html/unnamed-chunk-62-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Unlike in the case of the discrete random variable in which the height of the vertical bar in the probability histogram is defined to be the probability of observing that corresponding value, <strong>for any continuous random variable</strong>, we define the probability of an event that is defined based on an interval <span class="math inline">\([a, b]\)</span> to be</p>
<ul>
<li><p>$P(a &lt; X &lt; b) = $ the area of the region defined by <span class="math inline">\(a, b\)</span> and the density curve (see the above figure).</p></li>
<li><p>As a special case, <span class="math inline">\(P(X = c) = 0\)</span>. Moreover, <span class="math inline">\(P(X=c_1, c_2, c_3,\cdots )=0\)</span>. That is, <strong>the probability of observing countably many values of a continuous random variable is ALWAYS ZERO!</strong>.</p></li>
<li><p><strong>Two Basic Types of Questions</strong>: finding probabilities and quantiles.</p>
<ul>
<li><p><em>Finding probabilities</em>: for any given two values (including possibly one of or both <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span>), say <span class="math inline">\(a, b\)</span>, then <span class="math inline">\(P(a&lt;X&lt;b)=\)</span> area of the shaded region as shown in the above Figure. As a special case, if <span class="math inline">\(a = b\)</span>, then <span class="math inline">\(P(X = a) = 0\)</span>.</p></li>
<li><p><em>Finding quantiles</em>: for a given value, say <span class="math inline">\(x\)</span>, of <span class="math inline">\(X\)</span> (possibly including <span class="math inline">\(\infty\)</span> or <span class="math inline">\(-\infty\)</span>) and a probability, say <span class="math inline">\(p_0\)</span>, we can find the other value <span class="math inline">\(x_0\)</span> from <span class="math inline">\(P(x &lt; X &lt; x_0) = p_0\)</span> if (<span class="math inline">\(x \le x_0\)</span>). As a special case, if the given value is <span class="math inline">\(\infty\)</span> and <span class="math inline">\(-\infty\)</span> (both are not valid values of <span class="math inline">\(X\)</span>!), then <span class="math inline">\(x_0\)</span> that satisfies <span class="math inline">\(P(X &lt; x_0) = P(-\infty&lt;X&lt;x_0) = p_0\)</span> is called the <span class="math inline">\(100p_0^{th}\)</span> quantile (see the following figure).</p></li>
</ul></li>
</ul>
<p><img src="STA501EB_files/figure-html/unnamed-chunk-63-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>In the next section, we will introduce several distributions of special continuous random variables.</p>
</div>
</div>
<div id="special-continuous-distributions" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Special Continuous Distributions<a href="concepts-of-probability-distributions.html#special-continuous-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Four distributions will be used in this course. We introduce the first two of them: normal distribution and t-distribution.</p>
<div id="normal-distribution" class="section level3 hasAnchor" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Normal Distribution<a href="concepts-of-probability-distributions.html#normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The general normal distribution has a bell-shaped distribution as shown in the following figure. A normal distribution is uniquely determined by its mean and variance. We usually use notation <span class="math inline">\(N(\mu, \sigma^2)\)</span>, where <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span> are the mean and variance of the normal distribution. When <span class="math inline">\(\mu=0\)</span> and <span class="math inline">\(\sigma^2 =1\)</span>, the normal distribution <span class="math inline">\(N(0,1)\)</span> is called the <strong>standard normal distribution</strong>. The</p>
<p><img src="STA501EB_files/figure-html/unnamed-chunk-64-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li><strong>Two Types of Questions in Normal Distribution</strong> are related to the left-tail area and quantile. R has two functions for finding <strong>left-tail area</strong> and <strong>quantile</strong> for any given normal distribution.</li>
</ul>
<pre><code>pnorm(quantile, mean, sd)          
# The above function finds the left-tail area for a given quantile. 
# mu = mean, sd = standard deviation.
qnorm(left.tail.prob, mean, sd)    
# The above function finds the quantile for a given left-tail area.
# mu = mean, sd = standard deviation.</code></pre>
<ul>
<li><strong>Example 12</strong>: We find the left-tail area of general normal distributions <span class="math inline">\(X \to N(16, 4^2)\)</span>. <span class="math inline">\(P(X &lt; 13) = ?\)</span></li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="concepts-of-probability-distributions.html#cb65-1" tabindex="-1"></a>normal.left.tail <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">pnorm</span>(<span class="dv">13</span>, <span class="at">mean =</span> <span class="dv">16</span>, <span class="at">sd =</span> <span class="dv">4</span>),<span class="dv">4</span>)</span>
<span id="cb65-2"><a href="concepts-of-probability-distributions.html#cb65-2" tabindex="-1"></a>normal.left.tail</span></code></pre></div>
<pre><code>## [1] 0.2266</code></pre>
<p>*<strong>Example 13</strong>: We find the left-tail area of the standard normal distributions <span class="math inline">\(X \to N(0, 1)\)</span>. <span class="math inline">\(P(X &lt; 0.3) = ?\)</span></p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="concepts-of-probability-distributions.html#cb67-1" tabindex="-1"></a>sd.norm.left.tail <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">pnorm</span>(<span class="fl">0.3</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),<span class="dv">4</span>)</span>
<span id="cb67-2"><a href="concepts-of-probability-distributions.html#cb67-2" tabindex="-1"></a>sd.norm.left.tail</span></code></pre></div>
<pre><code>## [1] 0.6179</code></pre>
<p>We next give a graphical representation of the tail area in <strong>Example 12</strong> and <strong>Example 13</strong>.</p>
<p><img src="STA501EB_files/figure-html/unnamed-chunk-67-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li><strong>Example 14</strong>: Let <span class="math inline">\(X \to N(16, 4^2)\)</span>. Find <span class="math inline">\(P(13 &lt; X &lt;18) = ?\)</span>
The following R code calculates the probability. Note that <code>P(X&lt;18) = pnorm(18, 16, 4)</code> and <code>P(X&lt;13) = pnorm(13, 16, 4)</code>. Therefore <code>P(13 &lt; X &lt; 18) = pnorm(18, 16, 4) - pnorm(13, 16, 4)</code>. The probability is the area of the purple region. See the following Figure.</li>
</ul>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="concepts-of-probability-distributions.html#cb69-1" tabindex="-1"></a>p<span class="fl">.18</span> <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="dv">18</span>, <span class="dv">16</span>, <span class="dv">4</span>)</span>
<span id="cb69-2"><a href="concepts-of-probability-distributions.html#cb69-2" tabindex="-1"></a>p<span class="fl">.13</span> <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="dv">13</span>, <span class="dv">16</span>, <span class="dv">4</span>)</span>
<span id="cb69-3"><a href="concepts-of-probability-distributions.html#cb69-3" tabindex="-1"></a>p.<span class="fl">13.</span>to<span class="fl">.18</span> <span class="ot">=</span> <span class="fu">round</span>(p<span class="fl">.18</span> <span class="sc">-</span> p<span class="fl">.13</span>, <span class="dv">4</span>)</span>
<span id="cb69-4"><a href="concepts-of-probability-distributions.html#cb69-4" tabindex="-1"></a>p.<span class="fl">13.</span>to<span class="fl">.18</span></span></code></pre></div>
<pre><code>## [1] 0.4648</code></pre>
<p><img src="STA501EB_files/figure-html/unnamed-chunk-70-1.png" width="480" style="display: block; margin: auto;" /></p>
<ul>
<li><strong>Example 15</strong>: Consider the standard normal distribution <span class="math inline">\(N(0,1)\)</span>. Find <span class="math inline">\(z_0\)</span> if <span class="math inline">\(P(Z &gt; z_0) = 0.2345\)</span>. The answer is given in the following R code: <code>qnorm(0.2345, 0, 1)</code> or simply <code>qnorm(0.2345)</code>. The latter form does not specify <code>mean=</code> and <code>sd=</code> since the default <code>mean = 0</code> and <code>sd = 1</code>.</li>
</ul>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="concepts-of-probability-distributions.html#cb71-1" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.2345</span>, <span class="dv">0</span>, <span class="dv">1</span>)     </span></code></pre></div>
<pre><code>## [1] -0.7241071</code></pre>
<p>That is, <span class="math inline">\(23.45\%\)</span> of the values in the standard normal population are less than or equal to <span class="math inline">\(-0.7241\)</span> and <span class="math inline">\(23.45\%\)</span> are greater than or equal to <span class="math inline">\(-0.7241\)</span>.</p>
</div>
<div id="t-distribution" class="section level3 hasAnchor" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> t distribution<a href="concepts-of-probability-distributions.html#t-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The t distribution is symmetric with respect to the vertical axis with a mean of 0. The shape is <strong>ALWAYS</strong> flatter than the <strong>standard normal distribution</strong>. The shape of a t distribution is uniquely determined by the <strong>degrees of freedom</strong>. The following chart describes the relationship between the standard normal and t distributions.</p>
<p><img src="STA501EB_files/figure-html/unnamed-chunk-72-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>R has two functions for finding left-tail area (also called tail probability) and quantile:</p>
<pre><code>pt(quantile, df)         # left-tail probability (left-tail area)
qt(left-tail-area, df)   # quantile</code></pre>
<ul>
<li><strong>Example 16</strong>: Answer the following questions about t-distributions.
<ul>
<li>Consider <span class="math inline">\(t(10)\)</span>, t-distribution with 10 degrees of freedom. <span class="math inline">\(P(T&lt;1.95) = ?\)</span></li>
<li>Consider <span class="math inline">\(t(5)\)</span>, t-distribution with 10 degrees of freedom. What is <span class="math inline">\(t_0\)</span> if <span class="math inline">\(P(T&lt;t_0) = 0.575\)</span>?</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="concepts-of-probability-distributions.html#cb74-1" tabindex="-1"></a><span class="co"># problem 1</span></span>
<span id="cb74-2"><a href="concepts-of-probability-distributions.html#cb74-2" tabindex="-1"></a>problem01 <span class="ot">=</span> <span class="fu">pt</span>(<span class="fl">1.95</span>, <span class="at">df=</span><span class="dv">10</span>)</span>
<span id="cb74-3"><a href="concepts-of-probability-distributions.html#cb74-3" tabindex="-1"></a><span class="co"># Problem 2</span></span>
<span id="cb74-4"><a href="concepts-of-probability-distributions.html#cb74-4" tabindex="-1"></a>problem02 <span class="ot">=</span> <span class="fu">qt</span>(<span class="fl">0.575</span>, <span class="at">df =</span> <span class="dv">5</span>)</span>
<span id="cb74-5"><a href="concepts-of-probability-distributions.html#cb74-5" tabindex="-1"></a><span class="do">## display the two result</span></span>
<span id="cb74-6"><a href="concepts-of-probability-distributions.html#cb74-6" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">problem01 =</span> problem01, <span class="at">problem02 =</span> problem02)</span></code></pre></div>
<pre><code>##      problem01 problem02
## [1,] 0.9601258 0.1991374</code></pre>
<p>The above results are also reflected in the following figures.</p>
<p><img src="STA501EB_files/figure-html/unnamed-chunk-74-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="summary" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Summary<a href="concepts-of-probability-distributions.html#summary" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this module, we introduced some basic concepts of probability, random variables, and distributions of random variables. Left-tail probability and quantile of normal and t distributions are the most important quantities that will be used in this course. We also introduced R functions to calculate left-tail the probability and the quantile of normal and t distributions. These R functions are summarized in the following.</p>
<pre><code># normal distribution
pnorm(quantile, mean, sd) # for the left-tail probability of normal distribution
qnorm(left.tail.prob, mean, sd) # for the quantile of normal distribution

# t-distribution
pt(quantile, df)        # for the left-tail probability of normal distribution
qt(left.tail.prob, df)  # for the quantile of t distribution</code></pre>
<div id="numerical-examples-based-on-normal-and-t-distributions" class="section level3 hasAnchor" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> Numerical Examples Based on Normal and t Distributions<a href="concepts-of-probability-distributions.html#numerical-examples-based-on-normal-and-t-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>Example 17</strong>: In the United States, males between the ages of 40 and 49 eat on average 103.1 g of fat every day with a standard deviation of 4.32 g (“What we eat,” 2012). Assume that the amount of fat a person eats is normally distributed.</p>
<ol style="list-style-type: decimal">
<li>State the random variable.</li>
<li>Find the probability that a man in the age group of 40-49 in the U.S. eats more than 110 g of fat every day.</li>
<li>Find the probability that a man in the age group of 40-49 in the U.S. eats less than 93 g of fat every day.</li>
<li>Find the probability that a man in the age group of 40-49 in the U.S. eats less than 65 g of fat every day.</li>
<li>If you found a man in the age group of 40-49 in the U.S. who says he eats less than 65 g of fat every day, would you believe him? Why or why not?</li>
<li>What daily fat level do 5% of all men in the age group of 40-49 in the U.S. eat more than?</li>
</ol></li>
</ul>
<p><strong>Solution</strong>: We use R to find the answers to the above questions.</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(Y\)</span> = amount of fat a person eats every day.
Calculations of problems 2 - 6 are given in the following R code chunk.</li>
</ol>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="concepts-of-probability-distributions.html#cb77-1" tabindex="-1"></a>p2 <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">110</span>, <span class="at">mean =</span><span class="fl">103.1</span>, <span class="at">sd =</span> <span class="fl">4.32</span>)  <span class="co"># 1-left-tail-prob = right-tail-prob</span></span>
<span id="cb77-2"><a href="concepts-of-probability-distributions.html#cb77-2" tabindex="-1"></a>p3 <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="dv">93</span>, <span class="at">mean =</span><span class="fl">103.1</span>, <span class="at">sd =</span> <span class="fl">4.32</span>)      <span class="co"># left-tail probability</span></span>
<span id="cb77-3"><a href="concepts-of-probability-distributions.html#cb77-3" tabindex="-1"></a>p4 <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="dv">65</span>, <span class="at">mean =</span><span class="fl">103.1</span>, <span class="at">sd =</span> <span class="fl">4.32</span>)      <span class="co"># left-tail probability</span></span>
<span id="cb77-4"><a href="concepts-of-probability-distributions.html#cb77-4" tabindex="-1"></a>p5 <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="dv">65</span>, <span class="at">mean =</span><span class="fl">103.1</span>, <span class="at">sd =</span> <span class="fl">4.32</span>)      <span class="co"># left-tail probability</span></span>
<span id="cb77-5"><a href="concepts-of-probability-distributions.html#cb77-5" tabindex="-1"></a>p6 <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="fl">-0.05</span>, <span class="at">mean =</span><span class="fl">103.1</span>, <span class="at">sd =</span> <span class="fl">4.32</span>)  <span class="co"># quantile</span></span>
<span id="cb77-6"><a href="concepts-of-probability-distributions.html#cb77-6" tabindex="-1"></a>ans <span class="ot">=</span> <span class="fu">cbind</span>(<span class="at">problem2 =</span> <span class="fu">round</span>(p2,<span class="dv">4</span>), <span class="at">problem3 =</span>  <span class="fu">round</span>(p3,<span class="dv">4</span>), </span>
<span id="cb77-7"><a href="concepts-of-probability-distributions.html#cb77-7" tabindex="-1"></a>            <span class="at">problem4 =</span> <span class="fu">round</span>(p4,<span class="dv">4</span>), <span class="at">problem5 =</span>  <span class="fu">round</span>(p5,<span class="dv">4</span>), </span>
<span id="cb77-8"><a href="concepts-of-probability-distributions.html#cb77-8" tabindex="-1"></a>            <span class="at">problem6=</span> p6)</span>
<span id="cb77-9"><a href="concepts-of-probability-distributions.html#cb77-9" tabindex="-1"></a><span class="fu">row.names</span>(ans) <span class="ot">=</span><span class="st">&quot;prob or quantile&quot;</span></span>
<span id="cb77-10"><a href="concepts-of-probability-distributions.html#cb77-10" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">t</span>(ans))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">prob or quantile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">problem2</td>
<td align="right">0.0551</td>
</tr>
<tr class="even">
<td align="left">problem3</td>
<td align="right">0.0097</td>
</tr>
<tr class="odd">
<td align="left">problem4</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">problem5</td>
<td align="right">0.0000</td>
</tr>
<tr class="odd">
<td align="left">problem6</td>
<td align="right">110.2058</td>
</tr>
</tbody>
</table>
<ol start="2" style="list-style-type: decimal">
<li>The probability that a man in the age group of 40-49 in the U.S. eats more than 110 g of fat every day is 5.51%.</li>
<li>The probability that a man in the age group of 40-49 in the U.S. eats less than 93 g of fat every day is 0.997%.</li>
<li>The probability that a man in the age group of 40-49 in the U.S. eats less than 65 g of fat every day is close to 0.00%.</li>
<li>I will not believe a man in the age group of 40-49 in the U.S. who says he eats less than 65 g of fat every day because the chance of eating less than 65 g in that age group is almost 0.00%.</li>
<li>5% of all men in the age group of 40-49 in the U.S. eat more than 110.2058 g.</li>
</ol>
<ul>
<li><p><strong>Example 18</strong>: The mean cholesterol levels of women aged 45-59 in Ghana, Nigeria, and Seychelles is 5.1 mmol/l and the standard deviation is 1.0 mmol/l (Lawes, Hoorn, Law &amp; Rodgers, 2004). Assume that cholesterol levels are normally distributed.</p>
<ol style="list-style-type: decimal">
<li>State the random variable.</li>
<li>Find the probability that a woman aged 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level above 6.2 mmol/l (considered a high level).</li>
<li>Find the probability that a woman aged 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level below 5.2 mmol/l (considered a normal level).</li>
<li>Find the probability that a woman aged 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level between 5.2 and 6.2 mmol/l (considered borderline high).</li>
<li>If you found a woman aged 45-59 in Ghana, Nigeria, or Seychelles having a cholesterol level above 6.2 mmol/l, what could you conclude?</li>
<li>What value do 5% of all women ages 45-59 in Ghana, Nigeria, or Seychelles have a cholesterol level less than?</li>
</ol></li>
</ul>
<p><strong>Solution</strong></p>
<ol style="list-style-type: decimal">
<li>Random variable <span class="math inline">\(Y\)</span> = mean cholesterol levels of women aged 45-59 in Ghana, Nigeria, and Seychelles.</li>
</ol>
<p>The calculation of problems 2 - 6 is given in the following R code chunk.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="concepts-of-probability-distributions.html#cb78-1" tabindex="-1"></a>p2<span class="fl">.2</span> <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fl">6.2</span>, <span class="at">mean =</span> <span class="fl">5.1</span>, <span class="at">sd =</span> <span class="dv">1</span>)      <span class="co"># 1-left-tail-prob = right-tail-prob</span></span>
<span id="cb78-2"><a href="concepts-of-probability-distributions.html#cb78-2" tabindex="-1"></a>p2<span class="fl">.3</span> <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="fl">5.2</span>, <span class="at">mean =</span> <span class="fl">5.1</span>, <span class="at">sd =</span> <span class="dv">1</span>)         <span class="co"># left-tail probability</span></span>
<span id="cb78-3"><a href="concepts-of-probability-distributions.html#cb78-3" tabindex="-1"></a>p2<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">pnorm</span>(<span class="fl">6.2</span>, <span class="at">mean =</span> <span class="fl">5.1</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="sc">-</span>  <span class="fu">pnorm</span>(<span class="fl">5.2</span>, <span class="at">mean =</span> <span class="fl">5.1</span>, <span class="at">sd =</span> <span class="dv">1</span>)    </span>
<span id="cb78-4"><a href="concepts-of-probability-distributions.html#cb78-4" tabindex="-1"></a>p2<span class="fl">.5</span> <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span><span class="fu">pnorm</span>(<span class="fl">6.2</span>, <span class="at">mean =</span> <span class="fl">5.1</span>, <span class="at">sd =</span> <span class="dv">1</span>)      <span class="co"># left-tail probability</span></span>
<span id="cb78-5"><a href="concepts-of-probability-distributions.html#cb78-5" tabindex="-1"></a>p2<span class="fl">.6</span> <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="fl">0.05</span>, <span class="at">mean =</span> <span class="fl">5.1</span>, <span class="at">sd =</span> <span class="dv">1</span>)      <span class="co"># quantile</span></span>
<span id="cb78-6"><a href="concepts-of-probability-distributions.html#cb78-6" tabindex="-1"></a>ans.p2 <span class="ot">=</span> <span class="fu">cbind</span>(<span class="at">problem2 =</span> <span class="fu">round</span>(p2<span class="fl">.2</span>,<span class="dv">4</span>), <span class="at">problem3 =</span>  <span class="fu">round</span>(p2<span class="fl">.3</span>,<span class="dv">4</span>), </span>
<span id="cb78-7"><a href="concepts-of-probability-distributions.html#cb78-7" tabindex="-1"></a>               <span class="at">problem4 =</span> <span class="fu">round</span>(p2<span class="fl">.4</span>,<span class="dv">4</span>), <span class="at">problem5 =</span>  <span class="fu">round</span>(p2<span class="fl">.5</span>,<span class="dv">4</span>), </span>
<span id="cb78-8"><a href="concepts-of-probability-distributions.html#cb78-8" tabindex="-1"></a>               <span class="at">problem6 =</span> p2<span class="fl">.6</span>)</span>
<span id="cb78-9"><a href="concepts-of-probability-distributions.html#cb78-9" tabindex="-1"></a><span class="fu">row.names</span>(ans.p2) <span class="ot">=</span><span class="st">&quot;prob or quantile&quot;</span></span>
<span id="cb78-10"><a href="concepts-of-probability-distributions.html#cb78-10" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">t</span>(ans.p2))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">prob or quantile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">problem2</td>
<td align="right">0.135700</td>
</tr>
<tr class="even">
<td align="left">problem3</td>
<td align="right">0.539800</td>
</tr>
<tr class="odd">
<td align="left">problem4</td>
<td align="right">0.324500</td>
</tr>
<tr class="even">
<td align="left">problem5</td>
<td align="right">0.135700</td>
</tr>
<tr class="odd">
<td align="left">problem6</td>
<td align="right">3.455146</td>
</tr>
</tbody>
</table>
<ol start="2" style="list-style-type: decimal">
<li>The probability that a woman aged 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level above 6.2 mmol/l is 13.57%.</li>
<li>Find the probability that a woman aged 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level below 5.2 mmol/l is 53.98%.</li>
<li>Find the probability that a woman aged 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level between 5.2 and 6.2 mmol/l 32.45%.</li>
<li>If a woman aged 45-59 in Ghana, Nigeria, or Seychelles has a cholesterol level above 6.2 mmol/l, he has a high cholesterol level.</li>
<li>5% of all women ages 45-59 in Ghana, Nigeria, or Seychelles have a cholesterol level of less than 3.455 mmol/l.</li>
</ol>
</div>
</div>
<div id="assignment---probability-distributions" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> Assignment - Probability Distributions<a href="concepts-of-probability-distributions.html#assignment---probability-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We focus on the concepts of random variables and their corresponding distributions. Two basic types of questions are will face very often in this course are to find (1) left-tail probability (area under the density curve) and (2) quantile under given conditions for all continuous distributions. We present numerical examples of normal and t distributions in the last part of the class note. In this assignment, you will do problems similar to the last two examples. You can use the codes provided in the class note [HTML or PDF]. I also include RMD on the course web page but not required. In case some of you want to learn more advanced R coding, the source RMD is useful.</p>
<p><strong>kable()</strong> function is in library <strong>{knitr}</strong>. If you have not installed this package on your computer, you will receive an error <code>could not find function "kable" calls:</code>. The following screenshot shows how to install a package on your computer.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-77"></span>
<img src="img04/w04-install-pack.jpg" alt="Install Packages on computer." width="80%" />
<p class="caption">
Figure 5.4: Install Packages on computer.
</p>
</div>
<p>This assignment focuses on the two types of questions using normal distributions. Please prepare an R Markdown document to complete the assignment.</p>
<ul>
<li><strong>Problem 1</strong></li>
</ul>
<p>The size of fish is very important to commercial fishing. A study conducted in 2012 found the length of Atlantic cod caught in nets in Karlskrona to have a mean of 49.9 cm and a standard deviation of 3.74 cm (Ovegard, Berndt &amp; Lunneryd, 2012). Assume the length of fish is normally distributed.</p>
<ol style="list-style-type: decimal">
<li>State the random variable.</li>
<li>Find the probability that an Atlantic cod has a length of less than 52 cm.</li>
<li>Find the probability that an Atlantic cod has a length of more than 74 cm.</li>
<li>Find the probability that an Atlantic cod has a length between 40.5 and 57.5 cm.</li>
<li>If you found an Atlantic cod to have a length of more than 74 cm, what could you conclude?</li>
<li>What length are 15% of all Atlantic cod longer than?</li>
</ol>
<ul>
<li><strong>Problem 2</strong></li>
</ul>
<p>The mean yearly rainfall in Sydney, Australia, is about 137 mm and the standard deviation is about 69 mm (“Annual maximums of,” 2013). Assume rainfall is normally distributed.</p>
<ol style="list-style-type: decimal">
<li>State the random variable.</li>
<li>Find the probability that the yearly rainfall is less than 100 mm.</li>
<li>Find the probability that the yearly rainfall is more than 240 mm.</li>
<li>Find the probability that the yearly rainfall is between 140 and 250 mm.</li>
<li>If a year has a rainfall of less than 100mm, does that mean it is an unusually dry year? Why or why not?</li>
<li>What rainfall amounts are 90% of all yearly rainfalls more than?</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="descriptive-statistics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sampling-distributions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/pengdsci/STA501EB/edit/master/04-ConceptsOfDistributions.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["STA501EB.pdf", "STA501EB.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
